// AUTO-GENERATED by scripts/scrape-conventions.mjs — do not edit by hand.
// Run `npm run scrape:conventions` to refresh from https://hanabi.github.io.

export interface Convention {
  name: string;
  href: string;
}

export interface LevelConventions {
  level: number;
  conventions: Convention[];
}

export const conventionsByLevel: LevelConventions[] = [
  {
    "level": 1,
    "conventions": [
      {
        "name": "The Chop",
        "href": "https://hanabi.github.io/level-1#the-chop"
      },
      {
        "name": "The Definition of Playable",
        "href": "https://hanabi.github.io/level-1#the-definition-of-playable"
      },
      {
        "name": "The Definition of Trash",
        "href": "https://hanabi.github.io/level-1#the-definition-of-trash"
      },
      {
        "name": "Save Clues",
        "href": "https://hanabi.github.io/level-1#save-clues"
      },
      {
        "name": "Clue Focus",
        "href": "https://hanabi.github.io/level-1#clue-focus"
      },
      {
        "name": "Good Touch Principle",
        "href": "https://hanabi.github.io/level-1#good-touch-principle"
      },
      {
        "name": "Save Principle",
        "href": "https://hanabi.github.io/level-1#save-principle"
      },
      {
        "name": "Minimum Clue Value Principle",
        "href": "https://hanabi.github.io/level-1#minimum-clue-value-principle"
      },
      {
        "name": "The Early Game",
        "href": "https://hanabi.github.io/level-1#the-early-game"
      },
      {
        "name": "The 5 Save",
        "href": "https://hanabi.github.io/level-1#the-5-save"
      },
      {
        "name": "The 2 Save",
        "href": "https://hanabi.github.io/level-1#the-2-save"
      },
      {
        "name": "The Prompt",
        "href": "https://hanabi.github.io/level-1#the-prompt"
      },
      {
        "name": "The Finesse",
        "href": "https://hanabi.github.io/level-1#the-finesse"
      },
      {
        "name": "Finesse Position",
        "href": "https://hanabi.github.io/level-1#finesse-position"
      },
      {
        "name": "Finessed Cards",
        "href": "https://hanabi.github.io/level-1#finessed-cards"
      },
      {
        "name": "Prompts > Finesses",
        "href": "https://hanabi.github.io/level-1#prompts--finesses"
      },
      {
        "name": "Card Notes",
        "href": "https://hanabi.github.io/level-1#card-notes"
      },
      {
        "name": "Rewind",
        "href": "https://hanabi.github.io/level-1#rewind"
      },
      {
        "name": "Empathy",
        "href": "https://hanabi.github.io/level-1#empathy"
      }
    ]
  },
  {
    "level": 2,
    "conventions": [
      {
        "name": "The 5 Stall (Cluing Off Chop 5's)",
        "href": "https://hanabi.github.io/level-2#the-5-stall-cluing-off-chop-5s"
      },
      {
        "name": "The Double Prompt / Triple Prompt / Quadruple Prompt",
        "href": "https://hanabi.github.io/level-2#the-double-prompt--triple-prompt--quadruple-prompt"
      },
      {
        "name": "The Double Finesse / Triple Finesse / Quadruple Finesse",
        "href": "https://hanabi.github.io/level-2#the-double-finesse--triple-finesse--quadruple-finesse"
      },
      {
        "name": "The Prompt + Finesse",
        "href": "https://hanabi.github.io/level-2#the-prompt--finesse"
      },
      {
        "name": "The Reverse Finesse",
        "href": "https://hanabi.github.io/level-2#the-reverse-finesse"
      },
      {
        "name": "The Self-Finesse",
        "href": "https://hanabi.github.io/level-2#the-self-finesse"
      },
      {
        "name": "Trash",
        "href": "https://hanabi.github.io/level-2#trash"
      },
      {
        "name": "One-Away-From-Playable Cards",
        "href": "https://hanabi.github.io/level-2#one-away-from-playable-cards"
      },
      {
        "name": "Stomping on a Finesse",
        "href": "https://hanabi.github.io/level-2#stomping-on-a-finesse"
      },
      {
        "name": "What to Do After a Strike",
        "href": "https://hanabi.github.io/level-2#what-to-do-after-a-strike"
      },
      {
        "name": "The Wrong Prompt",
        "href": "https://hanabi.github.io/level-2#the-wrong-prompt"
      }
    ]
  },
  {
    "level": 3,
    "conventions": [
      {
        "name": "Playing Multiple 1's",
        "href": "https://hanabi.github.io/level-3#playing-multiple-1s"
      },
      {
        "name": "The Fix Clue",
        "href": "https://hanabi.github.io/level-3#the-fix-clue"
      },
      {
        "name": "The Fix Clue (That Touches Multiple Cards)",
        "href": "https://hanabi.github.io/level-3#the-fix-clue-that-touches-multiple-cards"
      },
      {
        "name": "The Fix Clue (That Gives No Additional Information)",
        "href": "https://hanabi.github.io/level-3#the-fix-clue-that-gives-no-additional-information"
      },
      {
        "name": "The Sarcastic Discard (SD)",
        "href": "https://hanabi.github.io/level-3#the-sarcastic-discard-sd"
      },
      {
        "name": "Misplay Cost Principle",
        "href": "https://hanabi.github.io/level-3#misplay-cost-principle"
      },
      {
        "name": "Efficiency",
        "href": "https://hanabi.github.io/level-3#efficiency"
      },
      {
        "name": "Tempo",
        "href": "https://hanabi.github.io/level-3#tempo"
      },
      {
        "name": "Information Lock Principle",
        "href": "https://hanabi.github.io/level-3#information-lock-principle"
      }
    ]
  },
  {
    "level": 4,
    "conventions": [
      {
        "name": "Chop Moves",
        "href": "https://hanabi.github.io/level-4#chop-moves"
      },
      {
        "name": "The Trash Chop Move (TCM)",
        "href": "https://hanabi.github.io/level-4#the-trash-chop-move-tcm"
      },
      {
        "name": "The 5's Chop Move (5CM)",
        "href": "https://hanabi.github.io/level-4#the-5s-chop-move-5cm"
      },
      {
        "name": "The Order Chop Move (OCM)",
        "href": "https://hanabi.github.io/level-4#the-order-chop-move-ocm"
      },
      {
        "name": "Chop Moves as a Category",
        "href": "https://hanabi.github.io/level-4#chop-moves-as-a-category"
      },
      {
        "name": "Chop Moves & New Clues",
        "href": "https://hanabi.github.io/level-4#chop-moves--new-clues"
      },
      {
        "name": "Chop Moves & Prompts",
        "href": "https://hanabi.github.io/level-4#chop-moves--prompts"
      },
      {
        "name": "Critical Discards after a Chop Move (Mistake)",
        "href": "https://hanabi.github.io/level-4#critical-discards-after-a-chop-move-mistake"
      },
      {
        "name": "Accidental Chop Moves (Mistake)",
        "href": "https://hanabi.github.io/level-4#accidental-chop-moves-mistake"
      }
    ]
  },
  {
    "level": 5,
    "conventions": [
      {
        "name": "Prompts in Multi-Color Variants",
        "href": "https://hanabi.github.io/level-5#prompts-in-multi-color-variants"
      },
      {
        "name": "The Hidden Finesse",
        "href": "https://hanabi.github.io/level-5#the-hidden-finesse"
      },
      {
        "name": "The Layered Finesse",
        "href": "https://hanabi.github.io/level-5#the-layered-finesse"
      },
      {
        "name": "The Clandestine Finesse",
        "href": "https://hanabi.github.io/level-5#the-clandestine-finesse"
      },
      {
        "name": "The Queued Finesse",
        "href": "https://hanabi.github.io/level-5#the-queued-finesse"
      },
      {
        "name": "The Ambiguous Finesse",
        "href": "https://hanabi.github.io/level-5#the-ambiguous-finesse"
      },
      {
        "name": "The Layered Finesse Dupe Clue",
        "href": "https://hanabi.github.io/level-5#the-layered-finesse-dupe-clue"
      },
      {
        "name": "Urgency Principle (Playing Into Finesses as Soon as Possible)",
        "href": "https://hanabi.github.io/level-5#urgency-principle-playing-into-finesses-as-soon-as-possible"
      },
      {
        "name": "Schrödinger's Cat Principle",
        "href": "https://hanabi.github.io/level-5#schrödingers-cat-principle"
      }
    ]
  },
  {
    "level": 6,
    "conventions": [
      {
        "name": "The Tempo Clue",
        "href": "https://hanabi.github.io/level-6#the-tempo-clue"
      },
      {
        "name": "The Valuable Tempo Clue",
        "href": "https://hanabi.github.io/level-6#the-valuable-tempo-clue"
      },
      {
        "name": "The Tempo Clue Stall (A Non-Valuable Tempo Clue)",
        "href": "https://hanabi.github.io/level-6#the-tempo-clue-stall-a-non-valuable-tempo-clue"
      },
      {
        "name": "The Tempo Clue Chop Move (TCCM)",
        "href": "https://hanabi.github.io/level-6#the-tempo-clue-chop-move-tccm"
      },
      {
        "name": "Chop Moves & Tempo Clues",
        "href": "https://hanabi.github.io/level-6#chop-moves--tempo-clues"
      },
      {
        "name": "Focus Shifting",
        "href": "https://hanabi.github.io/level-6#focus-shifting"
      },
      {
        "name": "Discard Modulation",
        "href": "https://hanabi.github.io/level-6#discard-modulation"
      },
      {
        "name": "The Value of One-Away-From-Playable Cards",
        "href": "https://hanabi.github.io/level-6#the-value-of-one-away-from-playable-cards"
      },
      {
        "name": "Clarity Principle",
        "href": "https://hanabi.github.io/level-6#clarity-principle"
      }
    ]
  },
  {
    "level": 7,
    "conventions": [
      {
        "name": "The Scream Discard Chop Move (SDCM)",
        "href": "https://hanabi.github.io/level-7#the-scream-discard-chop-move-sdcm"
      },
      {
        "name": "The Scream Discard Chop Move (With Known-Trash)",
        "href": "https://hanabi.github.io/level-7#the-scream-discard-chop-move-with-known-trash"
      },
      {
        "name": "The Shout Discard Chop Move",
        "href": "https://hanabi.github.io/level-7#the-shout-discard-chop-move"
      },
      {
        "name": "The Generation Discard",
        "href": "https://hanabi.github.io/level-7#the-generation-discard"
      },
      {
        "name": "Lines",
        "href": "https://hanabi.github.io/level-7#lines"
      },
      {
        "name": "The All 4's Test",
        "href": "https://hanabi.github.io/level-7#the-all-4s-test"
      },
      {
        "name": "The Definition of Riding",
        "href": "https://hanabi.github.io/level-7#the-definition-of-riding"
      },
      {
        "name": "Blind-Playing Chop Moved Cards",
        "href": "https://hanabi.github.io/level-7#blind-playing-chop-moved-cards"
      }
    ]
  },
  {
    "level": 8,
    "conventions": [
      {
        "name": "The End-Game",
        "href": "https://hanabi.github.io/level-8#the-end-game"
      },
      {
        "name": "No Chop Moves in the End-Game",
        "href": "https://hanabi.github.io/level-8#no-chop-moves-in-the-end-game"
      },
      {
        "name": "The Positional Discard (Indicating a Play with a Discard)",
        "href": "https://hanabi.github.io/level-8#the-positional-discard-indicating-a-play-with-a-discard"
      },
      {
        "name": "The Positional Misplay (Indicating a Play with a Misplay)",
        "href": "https://hanabi.github.io/level-8#the-positional-misplay-indicating-a-play-with-a-misplay"
      },
      {
        "name": "The Double Positional Misplay (Indicating Two Plays with a Misplay)",
        "href": "https://hanabi.github.io/level-8#the-double-positional-misplay-indicating-two-plays-with-a-misplay"
      },
      {
        "name": "The Distribution Clue",
        "href": "https://hanabi.github.io/level-8#the-distribution-clue"
      },
      {
        "name": "Team Distribution Principle",
        "href": "https://hanabi.github.io/level-8#team-distribution-principle"
      },
      {
        "name": "The Pace +1 Rule",
        "href": "https://hanabi.github.io/level-8#the-pace-1-rule"
      },
      {
        "name": "Burning (End-Game Stalling)",
        "href": "https://hanabi.github.io/level-8#burning-end-game-stalling"
      },
      {
        "name": "End-Game Strategy",
        "href": "https://hanabi.github.io/level-8#end-game-strategy"
      }
    ]
  },
  {
    "level": 9,
    "conventions": [
      {
        "name": "Stalling Situations",
        "href": "https://hanabi.github.io/level-9#stalling-situations"
      },
      {
        "name": "Allowable Stall Clues (Stall Table)",
        "href": "https://hanabi.github.io/level-9#allowable-stall-clues-stall-table"
      },
      {
        "name": "The Early Game (Severity 1 Stalling)",
        "href": "https://hanabi.github.io/level-9#the-early-game-severity-1-stalling"
      },
      {
        "name": "Double Discard Situations / Double Discard Avoidance (DDA) (Severity 2 Stalling)",
        "href": "https://hanabi.github.io/level-9#double-discard-situations--double-discard-avoidance-dda-severity-2-stalling"
      },
      {
        "name": "Locked Hands (Severity 3 Stalling)",
        "href": "https://hanabi.github.io/level-9#locked-hands-severity-3-stalling"
      },
      {
        "name": "Clues Given While at 8 Clues (Severity 4 Stalling)",
        "href": "https://hanabi.github.io/level-9#clues-given-while-at-8-clues-severity-4-stalling"
      },
      {
        "name": "The 5 Stall (Intermediate Section)",
        "href": "https://hanabi.github.io/level-9#the-5-stall-intermediate-section"
      },
      {
        "name": "The Fill-In Clue",
        "href": "https://hanabi.github.io/level-9#the-fill-in-clue"
      },
      {
        "name": "The Locked Hand Save (LHS)",
        "href": "https://hanabi.github.io/level-9#the-locked-hand-save-lhs"
      },
      {
        "name": "The Anxiety Play (Forcing a Locked Player to Play)",
        "href": "https://hanabi.github.io/level-9#the-anxiety-play-forcing-a-locked-player-to-play"
      },
      {
        "name": "The 8 Clue Save (8CS)",
        "href": "https://hanabi.github.io/level-9#the-8-clue-save-8cs"
      }
    ]
  },
  {
    "level": 10,
    "conventions": [
      {
        "name": "The Gentleman's Discard (GD)",
        "href": "https://hanabi.github.io/level-10#the-gentlemans-discard-gd"
      },
      {
        "name": "The Layered Gentleman's Discard",
        "href": "https://hanabi.github.io/level-10#the-layered-gentlemans-discard"
      },
      {
        "name": "The Baton Discard (BD)",
        "href": "https://hanabi.github.io/level-10#the-baton-discard-bd"
      },
      {
        "name": "The Sarcastic Finesse",
        "href": "https://hanabi.github.io/level-10#the-sarcastic-finesse"
      },
      {
        "name": "The Certain Finesse & The Certain Discard",
        "href": "https://hanabi.github.io/level-10#the-certain-finesse--the-certain-discard"
      },
      {
        "name": "The Composition Finesse",
        "href": "https://hanabi.github.io/level-10#the-composition-finesse"
      },
      {
        "name": "The Double Gentleman's Discard (Illegal)",
        "href": "https://hanabi.github.io/level-10#the-double-gentlemans-discard-illegal"
      }
    ]
  },
  {
    "level": 11,
    "conventions": [
      {
        "name": "The Bluff",
        "href": "https://hanabi.github.io/level-11#the-bluff"
      },
      {
        "name": "The Self-Bluff",
        "href": "https://hanabi.github.io/level-11#the-self-bluff"
      },
      {
        "name": "Bluffs Through Already-Clued Cards",
        "href": "https://hanabi.github.io/level-11#bluffs-through-already-clued-cards"
      },
      {
        "name": "Bob's Truth Principle (Part 1)",
        "href": "https://hanabi.github.io/level-11#bobs-truth-principle-part-1"
      },
      {
        "name": "Cathy's Connecting Principle (Part 2)",
        "href": "https://hanabi.github.io/level-11#cathys-connecting-principle-part-2"
      },
      {
        "name": "Guide Principle",
        "href": "https://hanabi.github.io/level-11#guide-principle"
      },
      {
        "name": "Clue Interpretation & Occam's Razor",
        "href": "https://hanabi.github.io/level-11#clue-interpretation--occams-razor"
      },
      {
        "name": "The Pang of Guilt",
        "href": "https://hanabi.github.io/level-11#the-pang-of-guilt"
      },
      {
        "name": "Mistaking a Layered Finesse for a Bluff",
        "href": "https://hanabi.github.io/level-11#mistaking-a-layered-finesse-for-a-bluff"
      },
      {
        "name": "Bluff Prompts / Prompt Bluffs (Illegal)",
        "href": "https://hanabi.github.io/level-11#bluff-prompts--prompt-bluffs-illegal"
      },
      {
        "name": "Queued Bluffs (Illegal)",
        "href": "https://hanabi.github.io/level-11#queued-bluffs-illegal"
      }
    ]
  },
  {
    "level": 12,
    "conventions": [
      {
        "name": "Assuming Asymmetric Information",
        "href": "https://hanabi.github.io/level-12#assuming-asymmetric-information"
      },
      {
        "name": "Duplication Responsibility",
        "href": "https://hanabi.github.io/level-12#duplication-responsibility"
      },
      {
        "name": "The Selfish Clue",
        "href": "https://hanabi.github.io/level-12#the-selfish-clue"
      },
      {
        "name": "The Selfish Finesse (A Finesse Through Your Own Hand)",
        "href": "https://hanabi.github.io/level-12#the-selfish-finesse-a-finesse-through-your-own-hand"
      },
      {
        "name": "The Ego Clue (Mistake)",
        "href": "https://hanabi.github.io/level-12#the-ego-clue-mistake"
      },
      {
        "name": "The Stale 1's Clue",
        "href": "https://hanabi.github.io/level-12#the-stale-1s-clue"
      },
      {
        "name": "Focus Inversion",
        "href": "https://hanabi.github.io/level-12#focus-inversion"
      },
      {
        "name": "Context",
        "href": "https://hanabi.github.io/level-12#context"
      },
      {
        "name": "Choosing Between Playable Cards",
        "href": "https://hanabi.github.io/level-12#choosing-between-playable-cards"
      },
      {
        "name": "Cluing 1's in the Early Game",
        "href": "https://hanabi.github.io/level-12#cluing-1s-in-the-early-game"
      }
    ]
  },
  {
    "level": 13,
    "conventions": [
      {
        "name": "The 3 Bluff",
        "href": "https://hanabi.github.io/level-13#the-3-bluff"
      },
      {
        "name": "The Critical Color Bluff (CCB)",
        "href": "https://hanabi.github.io/level-13#the-critical-color-bluff-ccb"
      },
      {
        "name": "The Hard Bluff",
        "href": "https://hanabi.github.io/level-13#the-hard-bluff"
      },
      {
        "name": "The Hard 3 Bluff",
        "href": "https://hanabi.github.io/level-13#the-hard-3-bluff"
      },
      {
        "name": "The Known Bluff",
        "href": "https://hanabi.github.io/level-13#the-known-bluff"
      },
      {
        "name": "The Good Touch Bluff",
        "href": "https://hanabi.github.io/level-13#the-good-touch-bluff"
      },
      {
        "name": "Legal Bluff-Targets",
        "href": "https://hanabi.github.io/level-13#legal-bluff-targets"
      }
    ]
  },
  {
    "level": 14,
    "conventions": [
      {
        "name": "Known-Trash Discard Order",
        "href": "https://hanabi.github.io/level-14#known-trash-discard-order"
      },
      {
        "name": "The Trash Order Chop Move (TOCM)",
        "href": "https://hanabi.github.io/level-14#the-trash-order-chop-move-tocm"
      },
      {
        "name": "The Shout Discard Order Chop Move",
        "href": "https://hanabi.github.io/level-14#the-shout-discard-order-chop-move"
      },
      {
        "name": "The Trash Push",
        "href": "https://hanabi.github.io/level-14#the-trash-push"
      },
      {
        "name": "The Trash Push Prompt & The Trash Push Finesse",
        "href": "https://hanabi.github.io/level-14#the-trash-push-prompt--the-trash-push-finesse"
      },
      {
        "name": "The Trash Finesse",
        "href": "https://hanabi.github.io/level-14#the-trash-finesse"
      },
      {
        "name": "The Reverse Trash Finesse",
        "href": "https://hanabi.github.io/level-14#the-reverse-trash-finesse"
      },
      {
        "name": "The Forced Gentleman's Discard Chop Move",
        "href": "https://hanabi.github.io/level-14#the-forced-gentlemans-discard-chop-move"
      },
      {
        "name": "The Trash Bluff",
        "href": "https://hanabi.github.io/level-14#the-trash-bluff"
      }
    ]
  },
  {
    "level": 15,
    "conventions": [
      {
        "name": "The Double Bluff",
        "href": "https://hanabi.github.io/level-15#the-double-bluff"
      },
      {
        "name": "The Triple Bluff (Illegal)",
        "href": "https://hanabi.github.io/level-15#the-triple-bluff-illegal"
      },
      {
        "name": "The Hard Double Bluff",
        "href": "https://hanabi.github.io/level-15#the-hard-double-bluff"
      },
      {
        "name": "The Pestilent Double Bluff (PDB)",
        "href": "https://hanabi.github.io/level-15#the-pestilent-double-bluff-pdb"
      },
      {
        "name": "Deferring a Bluff",
        "href": "https://hanabi.github.io/level-15#deferring-a-bluff"
      },
      {
        "name": "Deferring a Double Bluff",
        "href": "https://hanabi.github.io/level-15#deferring-a-double-bluff"
      },
      {
        "name": "A Table for Deferring Bluffs",
        "href": "https://hanabi.github.io/level-15#a-table-for-deferring-bluffs"
      },
      {
        "name": "Interaction between Bob's Truth Principle and Occam's Razor",
        "href": "https://hanabi.github.io/level-15#interaction-between-bobs-truth-principle-and-occams-razor"
      }
    ]
  },
  {
    "level": 16,
    "conventions": [
      {
        "name": "Ejections",
        "href": "https://hanabi.github.io/level-16#ejections"
      },
      {
        "name": "Discharges",
        "href": "https://hanabi.github.io/level-16#discharges"
      },
      {
        "name": "The 5 Color Ejection (5CE)",
        "href": "https://hanabi.github.io/level-16#the-5-color-ejection-5ce"
      },
      {
        "name": "The Unknown Trash Discharge (1-for-1 Form) (UTD)",
        "href": "https://hanabi.github.io/level-16#the-unknown-trash-discharge-1-for-1-form-utd"
      },
      {
        "name": "The Unknown Trash Discharge (2-for-1 Form) (UTD)",
        "href": "https://hanabi.github.io/level-16#the-unknown-trash-discharge-2-for-1-form-utd"
      },
      {
        "name": "The Unknown Dupe Discharge (UDD)",
        "href": "https://hanabi.github.io/level-16#the-unknown-dupe-discharge-udd"
      }
    ]
  },
  {
    "level": 17,
    "conventions": [
      {
        "name": "The Duplicitous Value Clue",
        "href": "https://hanabi.github.io/level-17#the-duplicitous-value-clue"
      },
      {
        "name": "The Duplicitous Blind-Play",
        "href": "https://hanabi.github.io/level-17#the-duplicitous-blind-play"
      },
      {
        "name": "The Duplicitous Tempo Clue",
        "href": "https://hanabi.github.io/level-17#the-duplicitous-tempo-clue"
      },
      {
        "name": "The Assisted Trash Chop Move",
        "href": "https://hanabi.github.io/level-17#the-assisted-trash-chop-move"
      },
      {
        "name": "The Time Travel Chop Move (Direct Form)",
        "href": "https://hanabi.github.io/level-17#the-time-travel-chop-move-direct-form"
      },
      {
        "name": "The Time Travel Chop Move (Blind-Play Form)",
        "href": "https://hanabi.github.io/level-17#the-time-travel-chop-move-blind-play-form"
      }
    ]
  },
  {
    "level": 18,
    "conventions": [
      {
        "name": "Elimination & Elimination Notes",
        "href": "https://hanabi.github.io/level-18#elimination--elimination-notes"
      },
      {
        "name": "Double Discard Elimination",
        "href": "https://hanabi.github.io/level-18#double-discard-elimination"
      },
      {
        "name": "2 Elimination",
        "href": "https://hanabi.github.io/level-18#2-elimination"
      },
      {
        "name": "The Elimination Blind-Play",
        "href": "https://hanabi.github.io/level-18#the-elimination-blind-play"
      },
      {
        "name": "The Elimination Play Clue",
        "href": "https://hanabi.github.io/level-18#the-elimination-play-clue"
      },
      {
        "name": "Interaction Between Elimination & Chop-Focus",
        "href": "https://hanabi.github.io/level-18#interaction-between-elimination--chop-focus"
      },
      {
        "name": "The Elimination Riding Deduction",
        "href": "https://hanabi.github.io/level-18#the-elimination-riding-deduction"
      },
      {
        "name": "The Riding Deduction Bluff",
        "href": "https://hanabi.github.io/level-18#the-riding-deduction-bluff"
      },
      {
        "name": "The Elimination Self-Chop Move",
        "href": "https://hanabi.github.io/level-18#the-elimination-self-chop-move"
      },
      {
        "name": "The Elimination Finesse",
        "href": "https://hanabi.github.io/level-18#the-elimination-finesse"
      },
      {
        "name": "Trash Touch Elimination (TTE)",
        "href": "https://hanabi.github.io/level-18#trash-touch-elimination-tte"
      }
    ]
  },
  {
    "level": 19,
    "conventions": [
      {
        "name": "The Low Score Phase and the Normal Score Phase",
        "href": "https://hanabi.github.io/level-19#the-low-score-phase-and-the-normal-score-phase"
      },
      {
        "name": "No Play Clues with a Number 5 Clue in the Low Score Phase",
        "href": "https://hanabi.github.io/level-19#no-play-clues-with-a-number-5-clue-in-the-low-score-phase"
      },
      {
        "name": "The Early 5's Chop Move",
        "href": "https://hanabi.github.io/level-19#the-early-5s-chop-move"
      },
      {
        "name": "The 5 Pull",
        "href": "https://hanabi.github.io/level-19#the-5-pull"
      },
      {
        "name": "The 5 Pull Prompt & The 5 Pull Finesse",
        "href": "https://hanabi.github.io/level-19#the-5-pull-prompt--the-5-pull-finesse"
      },
      {
        "name": "The 5 Pull Double Finesse",
        "href": "https://hanabi.github.io/level-19#the-5-pull-double-finesse"
      },
      {
        "name": "The 5 Pull Clandestine Finesse",
        "href": "https://hanabi.github.io/level-19#the-5-pull-clandestine-finesse"
      },
      {
        "name": "The 5 Pull Promise (A Play Clue After a 5 Pull)",
        "href": "https://hanabi.github.io/level-19#the-5-pull-promise-a-play-clue-after-a-5-pull"
      },
      {
        "name": "Finesses While 5 Pulled are Certain Finesses",
        "href": "https://hanabi.github.io/level-19#finesses-while-5-pulled-are-certain-finesses"
      },
      {
        "name": "The 5 Pull Skip",
        "href": "https://hanabi.github.io/level-19#the-5-pull-skip"
      },
      {
        "name": "The 5 Number Ejection (5NE)",
        "href": "https://hanabi.github.io/level-19#the-5-number-ejection-5ne"
      },
      {
        "name": "The 5 Number Discharge (5ND)",
        "href": "https://hanabi.github.io/level-19#the-5-number-discharge-5nd"
      },
      {
        "name": "The 5 Number Ejection Finesse Position Skips",
        "href": "https://hanabi.github.io/level-19#the-5-number-ejection-finesse-position-skips"
      },
      {
        "name": "A Flowchart for Cluing 5's",
        "href": "https://hanabi.github.io/level-19#a-flowchart-for-cluing-5s"
      },
      {
        "name": "Interaction Between 2 Saves & 5 Stalls",
        "href": "https://hanabi.github.io/level-19#interaction-between-2-saves--5-stalls"
      }
    ]
  },
  {
    "level": 20,
    "conventions": [
      {
        "name": "The Occupied Play Clue & The Occupied Finesse (OPC)",
        "href": "https://hanabi.github.io/level-20#the-occupied-play-clue--the-occupied-finesse-opc"
      },
      {
        "name": "The Out-of-Order Play Clue (Triple O / OOO)",
        "href": "https://hanabi.github.io/level-20#the-out-of-order-play-clue-triple-o--ooo"
      },
      {
        "name": "The Out-of-Order Finesse",
        "href": "https://hanabi.github.io/level-20#the-out-of-order-finesse"
      },
      {
        "name": "The Out-of-Order Corollary",
        "href": "https://hanabi.github.io/level-20#the-out-of-order-corollary"
      },
      {
        "name": "The Suboptimal Prompt & The Suboptimal Finesse & The Suboptimal Bluff",
        "href": "https://hanabi.github.io/level-20#the-suboptimal-prompt--the-suboptimal-finesse--the-suboptimal-bluff"
      },
      {
        "name": "The No-Information Finesse",
        "href": "https://hanabi.github.io/level-20#the-no-information-finesse"
      },
      {
        "name": "The No-Information Double Bluff (NIDB)",
        "href": "https://hanabi.github.io/level-20#the-no-information-double-bluff-nidb"
      }
    ]
  },
  {
    "level": 21,
    "conventions": [
      {
        "name": "Ignition",
        "href": "https://hanabi.github.io/level-21#ignition"
      },
      {
        "name": "Double Ignition (DI)",
        "href": "https://hanabi.github.io/level-21#double-ignition-di"
      },
      {
        "name": "The Replay Double Ignition (RDI)",
        "href": "https://hanabi.github.io/level-21#the-replay-double-ignition-rdi"
      },
      {
        "name": "The Trash Double Ignition (TDI)",
        "href": "https://hanabi.github.io/level-21#the-trash-double-ignition-tdi"
      },
      {
        "name": "The Poke Double Ignition (PDI)",
        "href": "https://hanabi.github.io/level-21#the-poke-double-ignition-pdi"
      },
      {
        "name": "The Chop Move Ignition (CMI) (with 1 card Chop Moved)",
        "href": "https://hanabi.github.io/level-21#the-chop-move-ignition-cmi-with-1-card-chop-moved"
      },
      {
        "name": "The Chop Move Ignition (CMI) (with 2+ cards Chop Moved)",
        "href": "https://hanabi.github.io/level-21#the-chop-move-ignition-cmi-with-2-cards-chop-moved"
      },
      {
        "name": "Bomb Double Ignition",
        "href": "https://hanabi.github.io/level-21#bomb-double-ignition"
      },
      {
        "name": "Bomb Triple Ignition",
        "href": "https://hanabi.github.io/level-21#bomb-triple-ignition"
      }
    ]
  },
  {
    "level": 22,
    "conventions": [
      {
        "name": "Phantom Playable Cards",
        "href": "https://hanabi.github.io/level-22#phantom-playable-cards"
      },
      {
        "name": "The Scream Discard for a Phantom Playable Card",
        "href": "https://hanabi.github.io/level-22#the-scream-discard-for-a-phantom-playable-card"
      },
      {
        "name": "The Sacrifice Discard",
        "href": "https://hanabi.github.io/level-22#the-sacrifice-discard"
      },
      {
        "name": "The Echo Scream Discard Chop Move (ESDCM)",
        "href": "https://hanabi.github.io/level-22#the-echo-scream-discard-chop-move-esdcm"
      },
      {
        "name": "The Echo Shout Discard (Illegal)",
        "href": "https://hanabi.github.io/level-22#the-echo-shout-discard-illegal"
      },
      {
        "name": "The Composition Discard",
        "href": "https://hanabi.github.io/level-22#the-composition-discard"
      },
      {
        "name": "The Rebellious Discard",
        "href": "https://hanabi.github.io/level-22#the-rebellious-discard"
      },
      {
        "name": "A Scream Discard Flowchart",
        "href": "https://hanabi.github.io/level-22#a-scream-discard-flowchart"
      }
    ]
  },
  {
    "level": 23,
    "conventions": [
      {
        "name": "Charms",
        "href": "https://hanabi.github.io/level-23#charms"
      },
      {
        "name": "The 4 Charm",
        "href": "https://hanabi.github.io/level-23#the-4-charm"
      },
      {
        "name": "The Blaze Discard",
        "href": "https://hanabi.github.io/level-23#the-blaze-discard"
      },
      {
        "name": "The Hesitation Blind-Play",
        "href": "https://hanabi.github.io/level-23#the-hesitation-blind-play"
      }
    ]
  },
  {
    "level": 24,
    "conventions": [
      {
        "name": "Trash Finesses and Trash Bluffs Are Always Unnecessary",
        "href": "https://hanabi.github.io/level-24#trash-finesses-and-trash-bluffs-are-always-unnecessary"
      },
      {
        "name": "Unnecessary Moves with Known Trash --> Ignition",
        "href": "https://hanabi.github.io/level-24#unnecessary-moves-with-known-trash----ignition"
      },
      {
        "name": "Unnecessary Moves with Unknown Trash Off Chop --> Chop Move",
        "href": "https://hanabi.github.io/level-24#unnecessary-moves-with-unknown-trash-off-chop----chop-move"
      },
      {
        "name": "Unnecessary Moves with Unknown Trash On Chop --> Trash Push",
        "href": "https://hanabi.github.io/level-24#unnecessary-moves-with-unknown-trash-on-chop----trash-push"
      },
      {
        "name": "Other Examples",
        "href": "https://hanabi.github.io/level-24#other-examples"
      }
    ]
  },
  {
    "level": 25,
    "conventions": [
      {
        "name": "The Priority Prompt & The Priority Finesse",
        "href": "https://hanabi.github.io/level-25#the-priority-prompt--the-priority-finesse"
      },
      {
        "name": "The Priority Bluff",
        "href": "https://hanabi.github.io/level-25#the-priority-bluff"
      },
      {
        "name": "The Layered Priority Finesse",
        "href": "https://hanabi.github.io/level-25#the-layered-priority-finesse"
      },
      {
        "name": "The Load Clue",
        "href": "https://hanabi.github.io/level-25#the-load-clue"
      },
      {
        "name": "The Paused Priority Finesse",
        "href": "https://hanabi.github.io/level-25#the-paused-priority-finesse"
      },
      {
        "name": "The Trust Finesse (A Priority Finesse From Playing an Unknown Card)",
        "href": "https://hanabi.github.io/level-25#the-trust-finesse-a-priority-finesse-from-playing-an-unknown-card"
      },
      {
        "name": "A Priority Flowchart (for Choosing Between 2+ Playable Cards)",
        "href": "https://hanabi.github.io/level-25#a-priority-flowchart-for-choosing-between-2-playable-cards"
      },
      {
        "name": "Priority with Blind-Plays",
        "href": "https://hanabi.github.io/level-25#priority-with-blind-plays"
      },
      {
        "name": "Priority with Both Known and Unknown Cards",
        "href": "https://hanabi.github.io/level-25#priority-with-both-known-and-unknown-cards"
      },
      {
        "name": "Situations Where Priority Does Not Apply",
        "href": "https://hanabi.github.io/level-25#situations-where-priority-does-not-apply"
      },
      {
        "name": "Playing Into Someone Else's Hand",
        "href": "https://hanabi.github.io/level-25#playing-into-someone-elses-hand"
      }
    ]
  }
];
