<!-- /lib/components/ConventionsModal.svelte -->
<!-- A quick-reference cheat sheet of the H-group conventions, indexed by level.
     Each entry links to its section on hanabi.github.io (opens in a new tab so
     the current game state is never disturbed). The data is generated by
     scripts/scrape-conventions.mjs into src/lib/data/conventions.ts. -->
<script lang="ts">
  import { conventionsByLevel } from "../data/conventions";

  export let isOpen = false;

  // Drop a leading "The " to save horizontal space in the chip list. The
  // underlying data keeps the full heading text; this is display-only.
  function shortName(name: string): string {
    return name.replace(/^The /, "");
  }

  function closePanel() {
    isOpen = false;
  }
</script>

{#if isOpen}
  <div class="modal-overlay" on:click={closePanel}>
    <div class="conventions-modal" on:click|stopPropagation>
      <div class="header">
        <h2>Conventions cheat sheet</h2>
        <button class="close-btn" on:click={closePanel}>Close</button>
      </div>
      <p class="subtitle">
        H-group conventions by level. Tap one to open its section on
        hanabi.github.io in a new tab.
      </p>
      <div class="scroll">
        {#each conventionsByLevel as { level, conventions }}
          <div class="level-row">
            <span class="level-label">Level {level}</span>
            {#each conventions as convention}
              <a href={convention.href} target="_blank" rel="noopener" title={convention.name}>
                {shortName(convention.name)}
              </a>
            {/each}
          </div>
        {/each}
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-overlay {
    z-index: 1000;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: rgba(0, 0, 0, 0.5);
    padding: 12px;
    box-sizing: border-box;
  }

  .conventions-modal {
    background-color: dimgray;
    color: white;
    padding: 16px;
    border-radius: 5px;
    border: 2px solid lightgray;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
    width: min(720px, 100%);
    max-height: 85vh;
    display: flex;
    flex-direction: column;
  }

  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
  }

  .header h2 {
    margin: 0;
    font-size: 1.2rem;
  }

  .close-btn {
    flex-shrink: 0;
    cursor: pointer;
  }

  .subtitle {
    margin: 4px 0 12px;
    font-size: 0.85rem;
    opacity: 0.85;
    text-align: left;
  }

  .scroll {
    overflow-y: auto;
    overflow-x: hidden;
    -webkit-overflow-scrolling: touch;
  }

  /* Each level is a left-justified, wrapping row: the "Level N" label is the
     first inline item, followed by the button-like convention links. */
  .level-row {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: flex-start;
    gap: 6px;
    padding: 8px 0;
  }

  .level-row + .level-row {
    border-top: 3px solid rgba(255, 255, 255, 0.2);
  }

  .level-label {
    font-weight: 600;
    white-space: nowrap;
    margin-right: 4px;
  }

  a {
    color: lightblue;
    text-decoration: none;
    background-color: rgba(0, 0, 0, 0.3);
    padding: 3px 8px;
    border-radius: 6px;
    overflow-wrap: anywhere;
  }

  a:hover {
    background-color: rgba(0, 0, 0, 0.5);
    text-decoration: underline;
  }
</style>
